-- This is for the table creations scripts

CREATE TABLE Users (
    userID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    joinDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Posts (
    postID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    userID UNIQUEIDENTIFIER NOT NULL,
    postContent VARCHAR(200) NOT NULL,
    dateAdded DATETIME NOT NULL DEFAULT GETDATE(),
    pictureUrl VARCHAR(50) NULL,
    FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);

CREATE TABLE Comments (
    commentID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    userID UNIQUEIDENTIFIER NOT NULL,
    postID UNIQUEIDENTIFIER NOT NULL,
    commentContent VARCHAR(500) NOT NULL,
    dateAdded DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE,
    FOREIGN KEY (postID) REFERENCES Posts(postID) ON DELETE CASCADE
);
